### ISSUE TITLE
nell dataset issue

### ISSUE THREAD

**Issue by Junfeng-Hu** [tkipf/gcn#112] opened 2019-05-06 01:22 UTC
Could I ask how you process 'nell' dataset in your paper, cause I  use the 'nell' dataset, but I encountered 'row index  out of bounds' error, is there any problem I should mind when I process the 'nell ' dataset?

**Comment by tkipf** [comment] 2019-05-06 07:51
Duplicate of https://github.com/tkipf/gcn/issues/14

**Closed by tkipf** 2019-05-06 07:51 UTC
